background_opacity 0.80
font_family JetBrainsMono Nerd Font
window_padding_width 5 3
foreground            #4B09F5
background            #000000
selection_foreground  #000000
selection_background  #02C939