; COLORS KEYS DESCRIPTION
; text               =  Main field text; playlist names in main field and sidebar; headings.
; subtext            =  Text in main sidebar buttons; playlist names in sidebar; artist names and mini infos.
; main               =  Main field background.
; main-elevated      =  Backgrounds for objects above the main field.
; highlight          =  Highlight background for hovering over objects.
; highlight-elevated =  Highlight colors for objects above the main field.
; sidebar            =  Sidebar background.
; player             =  Player background.
; card               =  Card background on hover; player area outline.
; shadow             =  Card drop shadow; button background.
; selected row       =  Color of selected song, scrollbar, caption and playlist details, download and options buttons.
; button             =  Playlist button background in sidebar; drop-down menus; now playing song; play button background; like button.
; button-active      =  Active play button background.
; button-disabled    =  Seekbar and volume bar background.
; tab-active         =  Tabbar active item background in header.
; notification       =  Notification toast.
; notification-error =  Error notification toast.
; misc               =  Miscellaneous.

; [Psycho]
; ; Red on dark grey background
; text               = c20000
; subtext            = ffffff
; nav-active-text    = 101010
; main               = 101010
; sidebar            = 171717
; player             = 171717
; card               = 171717
; shadow             = 000000
; main-secondary     = 1f1f1f
; button             = c20000
; button-secondary   = a20606
; button-active      = c20000
; button-disabled    = 404040
; nav-active         = 9f0909
; play-button        = c20000
; tab-active         = 171717
; notification       = 5e0000
; notification-error = 5e0000
; playback-bar       = c20000
; misc               = FFFFFF
;
[UltraBlack]
; White on black background
text               = 4c09f5
subtext            = DEDEDE
nav-active-text    = 000000
main               = 000000
sidebar            = 000000
player             = 000000
card               = 000000
shadow             = 000000
main-secondary     = 292929
button             = 4c09f5
button-secondary   = DEDEDE
button-active      = 4c09f5
button-disabled    = 2f2f2f
nav-active         = DEDEDE
play-button        = DEDEDE
tab-active         = 292929
notification       = 292929
notification-error = 292929
playback-bar       = 4c09f5
