-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Lenovo Group Limited 0x403A",
  mode = "1920x1200@60.00",
  position = "0x0",
  scale = 1.5,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
